### PR TITLE
Use  get-host-by-name() instead of get-host-by-addr()

### PR DESCRIPTION
**Pull request by d-buchmann**
Try resolving host name instead of `gethostbyaddr`
For me this fixes joining a domain by CLI.

### CODE REVIEW

**Comment by pmhahn** [comment]
@edamrose This is [Bug #52726](https://forge.univention.org/bugzilla/show_bug.cgi?id=52726).

@d-buchmann Can you please provide some extra information on how you got into the error?
The traceback would be extremely helpful. Please provide the output of these commands:
```
python3 -c 'print(__import__("socket").gethostbyaddr(__import__("sys").argv[1]))' "name-your-Primary-DC-here"
python3 -c 'print(__import__("socket").gethostbyname(__import__("sys").argv[1]))'' "name-your-Primary-DC-here"
```

**Comment by d-buchmann** [comment]
Thanks for the hint towards that bug, I didn't notice it before.

From `/var/log/univention/domain-join.cli.log`:
```
Traceback (most recent call last):
  File "/usr/sbin/univention-domain-join-cli", line 189, in <module>
    distribution_joiner.join_domain()
  File "/usr/lib/python3/dist-packages/univention_domain_join/distributions/ubuntu.py", line 108, in join_domain
    raise DcResolveException('The UCS master name %s can not be resolved, please check your DNS settings' % self.ldap_master)
univention_domain_join.distributions.ubuntu.DcResolveException: The UCS master name ucs.domain.tld can not be resolved, please check your DNS settings
```

Honestly, I didn't go into detail, I just realized that name resolving should be getting an IP from a hostname, not vice versa.
When I execute your commands I see that `gethostbyaddr` actually does both:

```
root@ucs:/# python3 -c 'print(__import__("socket").gethostbyaddr(__import__("sys").argv[1]))' "ucs.domain.tld"
('ucs.domain.tld', [], ['192.168.0.xxx'])
```
Interestingly, this doesn't raise an Exception here, as the traceback implies. 
Same output if I put in the IP (supposedly that's the reason this is used instead of resolution by name).

```
root@ucs:/# python3 -c 'print(__import__("socket").gethostbyname(__import__("sys").argv[1]))' "ucs.domain.tld"
192.168.0.xxx
```

But this does NOT raise an error if given e.g. an empty string; it instead returns 0.0.0.0.
So I guess the culprit is a wrong parameter in the UCR (ldap_master being empty or not read correctly from the script - I didn't check that).
IIRC I also had to supply the DC's IP explicitly, that would explain why the join workedin the end despite the actual address resolution didn't.

**Comment by d-buchmann** [comment]
Anyway, after this little investigation I see that my PR is in no way a good solution for this, therefore closing.

**Comment by aBrAEUMER** [comment]
By the way: `gethostbyname()`works with the ip address as the argument as well. It simply returns this ip address. I think this is exactly what `name_is_resolvable` is meant for.

**Comment by pmhahn** [comment]
Finally I can reproduce this:
- :heavy_check_mark: `python3 -c 'import socket;socket.gethostbyname("forge.univention.org")'`
- :red_circle: `python3 -c 'import socket;socket.gethostbyaddr("forge.univention.org")'`

The root cause is the `label` → `IPv4` works (there is a DNS-`A`-RR), but `IPv4` → `label` does **not** work (there is **no** DNS-`PTR`-RR):
```
$ dig forge.univention.org.
;forge.univention.org.          IN      A
forge.univention.org.   3509    IN      A       78.138.66.7
$ dig -x 78.138.66.7
;7.66.138.78.in-addr.arpa.      IN      PTR
```

So `gethostbyaddr()` fails if there is no DNS-`PTR`-RR for the given DC.

See [Bug #52726](https://forge.univention.org/bugzilla/show_bug.cgi?id=52726#c9) for my complete analysis.

**Pull request closed without merging**
